/*Generated by FEBio Studio 3.0.0*/

#include <FECore/FEModel.h>
#include "FEBioFuseStudy.h"
#include <FECore/log.h>
#include <FECore/FECoreKernel.h>
#include <iostream>
using namespace std;

BEGIN_FECORE_CLASS(FEBioFuseStudy, FECoreStudy)
	ADD_PROPERTY(m_fuse.models, "models")->SetDefaultType("fuse_model_list");
	ADD_PROPERTY(m_fuse.exchanges, "exchanges")->SetDefaultType("fuse_exchanges");
	ADD_PROPERTY(m_strategy, "strategy")->SetFlags(FEProperty::Optional);
END_FECORE_CLASS();

static bool coupling_cb(FEModel* fem, unsigned int nwhen, void* data)
{
	FEBioFuseStudy* s = (FEBioFuseStudy*)data;
	return s->RunCoupling();
}

FEBioFuseStudy::FEBioFuseStudy(FEModel* fem) : FECoreStudy(fem), m_fuse(fem)
{
#ifndef NDEBUG
	fem->SetVerboseMode(true);
#endif
}

bool FEBioFuseStudy::Init()
{
	if (!InitModels())
	{
		feLog("Failed to initialize models.\n");
		return false;
	}

	if (m_strategy == nullptr)
	{
		m_strategy = fecore_new_class<FESolutionStrategy>("FETimeDecoupledStrategy", GetFEModel());
	}
	if (!m_strategy->Init())
	{
		feLog("Failed to initialize solution strategy.\n");
		return false;
	}

	// get the primary FE model
	FEModel* fem = GetFEModel();

	// TODO: make any necessary changes to the model
	fem->AddCallback(coupling_cb, CB_UPDATE_TIME, this);

	// Then, initialize the model
	return fem->Init();
}

bool FEBioFuseStudy::Execute()
{
	FEModel* fem = GetFEModel();

	// TODO: This function is called by FEBio and should execute the task's logic.
	//       To run the forward model, call FEModel::Solve()
	//       To reset the model, call FEModel::Reset()
	return fem->Solve();
}

bool FEBioFuseStudy::InitModels()
{
	if (m_fuse.models.empty()) return true;

	FEModel* fem = GetFEModel(); // primary model
	m_fuse.models.SetPrimaryModel(fem);
	string primaryName = m_fuse.models.primaryModel.name;
	if (primaryName.empty() == false)
		fem->SetName(m_fuse.models.primaryModel.name);

	for (SecondaryModel& mdl : m_fuse.models)
	{
		if (!mdl.InitModel())
		{
			std::cerr << "Failed to initialize model: " << mdl.name << std::endl;
			return false;
		}
	}

	// resolve couplings
	for (DataExchange& dex : m_fuse.exchanges)
	{
		if (!dex.InitExchange(m_fuse.models))
		{
			std::cerr << "Failed to initialize data exchange.\n";
			return false;
		}
	}

	// Now that we've been able to read them all in,
	// let's initialize them
	for (SecondaryModel& mdl : m_fuse.models)
	{
		assert(mdl.fem);
		if (mdl.fem->Init() == false)
		{
			std::cerr << "Failed to initialize model :\"" << mdl.name << "\"\n";
			return false;
		}
	}

	FECoreKernel& fecore = FECoreKernel::GetInstance();
	string moduleName;

	// setup plot files
	for (SecondaryModel& mdl : m_fuse.models)
	{
		FEBioPlotFile* xplt = new FEBioPlotFile(mdl.fem.get());

		moduleName = mdl.fem->GetModuleName();
		fecore.SetActiveModule(moduleName.c_str());

		string fileName = mdl.name + ".xplt";
		if (!xplt->Open(fileName.c_str()))
		{
			delete xplt;
			return false;
		}
		mdl.plt = std::shared_ptr<FEBioPlotFile>(xplt);
		mdl.plt->Write(0.f);
	}

	// restore correct module for the primary model
	moduleName = GetFEModel()->GetModuleName();
	fecore.SetActiveModule(moduleName.c_str());

	return true;
}

bool FEBioFuseStudy::RunCoupling()
{
	return m_strategy->RunCoupling(m_fuse);
}

void FEBioFuseStudy::BuildReport(FEBioReport& report)
{
	FEReportSection& outSec = report.AddSection("Output");
	outSec.AddText("The following output files were generated:");
	for (SecondaryModel& mdl : m_fuse.models)
	{
		if (mdl.plt)
		{
			outSec.AddFile(mdl.plt->GetFilename(), mdl.name);
		}
	}
}
