/*Generated by FEBio Studio 3.0.0*/

#include <FECore/FECoreStudy.h>
#include <FECore/FEModel.h>
#include <FECore/FECoreClass.h>
#include "Model.h"
#include "DataExchange.h"
#include "DataExchangeList.h"
#include "ModelList.h"
#include "SolutionStrategy.h"
#include "FuseModel.h"

class FEBioFuseStudy : public FECoreStudy
{
public:
	FEBioFuseStudy(FEModel* fem);

	bool Init() override;

	bool Execute() override;

	bool RunCoupling();

private:
	bool InitModels();

	void BuildReport(FEBioReport& report) override;

private:
	FuseModel m_fuse;
	FESolutionStrategy* m_strategy = nullptr;

	DECLARE_FECORE_CLASS();
};
