/*Generated by FEBio Studio 3.0.0*/

#include <FECore/FECoreTask.h>
#include <FECore/FEModel.h>
#include <FECore/FECoreClass.h>
#include "Model.h"
#include "DataExchange.h"
#include "DataExchangeList.h"
#include "ModelList.h"

class FECoupledSolver : public FECoreTask
{
public:
	FECoupledSolver(FEModel* fem);

	bool Init(const char* szfile) override;

	bool Run() override;

	bool RunCoupling();

private:
	bool ParseControlFile(const char* szfile);

	bool InitModels();

private:
	std::string m_version;

	ModelList m_models;
	DataExchangeList m_exchanges;

	DECLARE_FECORE_CLASS();
};
