/*Generated by FEBio Studio 3.0.0*/

#include <FECore/FECoreKernel.h>
#include "version.h"
#include <FECore/sdk.h>
#include "FECoupledSolver.h"
#include "SolutionStrategy.h"

FECORE_EXPORT unsigned int GetSDKVersion()
{
	return FE_SDK_VERSION;
}

FECORE_PLUGIN void GetPluginVersion(int& major, int& minor, int& patch)
{
	major = VERSION;
	minor = SUBVERSION;
	patch = SUBSUBVERSION;
}

FECORE_EXPORT void PluginInitialize(FECoreKernel& febio)
{
	FECoreKernel::SetInstance(&febio);
	febio.SetActiveModule(0);

	REGISTER_FECORE_CLASS(FECoupledSolver, "fuse");

	REGISTER_FECORE_CLASS(FETimeDecoupledStrategy, "time-decoupled");
}
