/*Generated by FEBio Studio 3.0.0*/

#include <FECore/FECoreKernel.h>
#include "version.h"
#include <FECore/sdk.h>
#include "FEBioFuseStudy.h"
#include "SolutionStrategy.h"

FECORE_EXPORT unsigned int GetSDKVersion()
{
	return FE_SDK_VERSION;
}

FECORE_PLUGIN void GetPluginVersion(int& major, int& minor, int& patch)
{
	major = VERSION;
	minor = SUBVERSION;
	patch = SUBSUBVERSION;
}

FECORE_EXPORT void PluginInitialize(FECoreKernel& febio)
{
	FECoreKernel::SetInstance(&febio);
	febio.SetActiveModule(0);

	REGISTER_FECORE_CLASS(FEBioFuseStudy, "fuse");
	REGISTER_FECORE_CLASS(ModelList, "fuse_model_list");
	REGISTER_FECORE_CLASS(PrimaryModel, "fuse_primary_model");
	REGISTER_FECORE_CLASS(SecondaryModel, "fuse_secondary_model");
	REGISTER_FECORE_CLASS(DataExchangeList, "fuse_exchanges");
	
	REGISTER_FECORE_CLASS(MapDataExchange, "map-to-map");
	REGISTER_FECORE_CLASS(ParamExchange, "param-to-param");

	REGISTER_FECORE_CLASS(FETimeDecoupledStrategy, "time-decoupled");
}
